version: "3.9"

services:

  inventory-api:
    image: inventory-api:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
    environment:
      - DATABASE_URL=postgresql://inventory_user:inventory_password@db:5432/inventory_db
    ports:
      - "8000:8000"
    networks:
      - backend_net
      - frontend_net


  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=inventory_db
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=inventory_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - backend_net


  adminer:
    image: adminer
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
    networks:
      - backend_net


  frontend:
    image: inventory-frontend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
    ports:
      - "80:80"
    networks:
      - frontend_net
      - backend_net


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "9110:8080"
    deploy:
      replicas: 1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring_net
      - backend_net


# --- Networks ---
networks:
  backend_net:
    driver: overlay
  frontend_net:
    driver: overlay
  monitoring_net:
    driver: overlay


# --- Volumes ---
volumes:
  postgres_data:
